# Generated by Django 3.2.5 on 2021-09-26 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covax', models.IntegerField()),
                ('coshield', models.IntegerField()),
                ('bed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('number', models.BigIntegerField()),
                ('department', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('offday', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Inpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=11)),
                ('roomno', models.IntegerField()),
                ('doctorname', models.CharField(max_length=20)),
                ('medicalcard', models.BooleanField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('number', models.BigIntegerField()),
                ('department', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('offday', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Outpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('doctorname', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='stafflogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
