# Generated by Django 3.2.5 on 2021-09-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0003_auto_20210926_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatient',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
