# Generated by Django 3.2.5 on 2021-09-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0004_outpatient_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='token',
            field=models.IntegerField(default=100),
        ),
    ]
