# Generated by Django 3.2.5 on 2021-09-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0005_auto_20210927_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient',
            name='medical_record',
            field=models.TextField(default=' '),
        ),
    ]
