# Generated by Django 3.2.5 on 2021-09-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0006_inpatient_medical_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatient',
            name='medical_record',
            field=models.TextField(default='Null'),
        ),
    ]
