# Generated by Django 3.2.5 on 2021-09-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0009_alter_inpatient_medical_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatient',
            name='medical_record',
            field=models.CharField(default='No Records', max_length=200),
        ),
    ]
