# Generated by Django 3.2.5 on 2021-09-27 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0012_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='dt',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
