# Generated by Django 3.2.5 on 2021-09-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0013_medicalrecord_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inpatient',
            name='medical_record',
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='roomno',
            field=models.IntegerField(unique=True),
        ),
    ]
