# Generated by Django 3.2.5 on 2021-09-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0015_auto_20210929_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctorlog',
        ),
    ]
