# Generated by Django 3.2.5 on 2021-10-01 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0016_delete_doctorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('pres', models.TextField(max_length=500)),
                ('dt', models.DateField(default=datetime.date(2021, 10, 1))),
            ],
        ),
    ]
