# Generated by Django 3.2.5 on 2021-10-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0018_prescription_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prescription',
            new_name='pharmacy',
        ),
    ]
