# Generated by Django 3.2.5 on 2021-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0019_rename_prescription_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='contact',
            field=models.BigIntegerField(default=0),
        ),
    ]
