# Generated by Django 3.2.5 on 2021-10-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0020_alter_pharmacy_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medname', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
