# Generated by Django 3.2.5 on 2021-10-01 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0021_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='dt',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 14, 53, 18, 719920)),
        ),
    ]
