# Generated by Django 3.2.5 on 2021-10-01 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0022_alter_pharmacy_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='dt',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 9, 24, 39, 445637, tzinfo=utc)),
        ),
    ]
