# Generated by Django 3.2.5 on 2021-10-01 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0024_auto_20211001_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicine',
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dt',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 9, 44, 52, 753816, tzinfo=utc)),
        ),
    ]
