# Generated by Django 3.2.5 on 2021-10-01 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0026_auto_20211001_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='medname',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dt',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 14, 34, 183001, tzinfo=utc)),
        ),
    ]
