# Generated by Django 3.2.5 on 2021-10-01 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0027_auto_20211001_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dt',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 42, 25, 889860, tzinfo=utc)),
        ),
    ]
