# Generated by Django 3.2.5 on 2021-10-01 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0028_auto_20211001_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='medname',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pres',
            field=models.TextField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dt',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 17, 6, 21, 857539, tzinfo=utc)),
        ),
    ]
