# Generated by Django 3.2.5 on 2021-10-02 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0030_auto_20211001_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patid', models.IntegerField()),
                ('operation', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('roomrent', models.IntegerField()),
                ('misc', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('lab', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dt',
            field=models.DateField(default=datetime.datetime(2021, 10, 2, 12, 32, 40, 835305, tzinfo=utc)),
        ),
    ]
