# Generated by Django 3.2.5 on 2021-10-02 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0032_auto_20211002_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('roomrent', models.IntegerField()),
                ('pharmbill', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dt',
            field=models.DateField(default=datetime.datetime(2021, 10, 2, 12, 41, 30, 81780, tzinfo=utc)),
        ),
    ]
