# Generated by Django 3.2.5 on 2021-10-02 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0033_auto_20211002_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='offday',
            field=models.DateField(default=datetime.date(2021, 10, 2)),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='date',
            field=models.DateField(default=datetime.date(2021, 10, 2)),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='dt',
            field=models.DateField(default=datetime.date(2021, 10, 2)),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='offday',
            field=models.DateField(default=datetime.date(2021, 10, 2)),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='date',
            field=models.DateField(default=datetime.date(2021, 10, 2)),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dt',
            field=models.DateField(default=datetime.date(2021, 10, 2)),
        ),
    ]
