# Generated by Django 3.2.5 on 2021-10-02 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0034_auto_20211002_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge',
            name='patid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='offday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
