# Generated by Django 3.2.5 on 2021-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0035_auto_20211002_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient',
            name='discharged',
            field=models.BooleanField(default=False),
        ),
    ]
