# Generated by Django 3.2.5 on 2021-10-04 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0036_inpatient_discharged'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatient',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='date',
            field=models.DateField(default=datetime.date(2021, 10, 4)),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='dt',
            field=models.DateField(default=datetime.date(2021, 10, 4)),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='offday',
            field=models.DateField(default=datetime.date(2021, 10, 4)),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='date',
            field=models.DateField(default=datetime.date(2021, 10, 4)),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dt',
            field=models.DateField(default=datetime.date(2021, 10, 4)),
        ),
    ]
