# Generated by Django 3.2.5 on 2021-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0037_auto_20211004_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpatient',
            name='paid',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
