# Generated by Django 3.2.5 on 2021-10-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0038_auto_20211004_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
