# Generated by Django 3.2.5 on 2021-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0039_discharge_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatient',
            name='presc',
            field=models.BooleanField(default=False),
        ),
    ]
