# Generated by Django 3.2.5 on 2021-10-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladminapp', '0041_adminlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminlog',
        ),
    ]
